window.MARCAS = window.MARCAS || {};
window.MARCAS.refugio = {
  id: 'refugio',
  catalogId: 'refugio-v1',
  name: 'Comunidade Anglicana Refúgio',
  shortName: 'Refúgio',
  handle: '@anglicana_refugio',
  cssClass: 'marca-refugio',
  assetBase: 'marcas/refugio/',
  allowTweaks: true,
  tweakControls: ['palette', 'accent', 'fontScale'],
  palettes: {
    clareira: { label: 'Clareira', paper: '#F5F1E4', ink: '#4A5B45' },
    seiva:    { label: 'Seiva',    paper: '#E8F2E4', ink: '#3A4A36' },
    oliva:    { label: 'Oliva',    paper: '#4A5B45', ink: '#F5F1E4' },
    noite:    { label: 'Noite',    paper: '#2A3328', ink: '#F5F1E4' },
  },
  accents: {
    sage:  { label: 'Sage',  color: '#A7CF9A' },
    soft:  { label: 'Soft',  color: '#C5E0BB' },
    ambar: { label: 'Âmbar', color: '#E0A85E' },
    oliva: { label: 'Oliva', color: '#4A5B45' },
  },
  tweakDefaults: { palette: 'clareira', accent: 'sage', fontScale: 1 },
  previewShell: 'post',
  hasCanvas: false,
  exportPixelRatio: 1,
  exportFilePrefix: 'refugio',
  exportBg: '#F5F1E4',
  barTheme: 'refugio',
  get logoIcon() { return window.RefugioIcons?.IconSelo; },
  get templates() { return window.REFUGIO_TEMPLATES || []; },
  get galleries() { return window.REFUGIO_GALLERIES || { photos: [], icons: [] }; },
};
