window.MARCAS = window.MARCAS || {};
window.MARCAS.reconciliador = {
  id: 'reconciliador',
  catalogId: 'reconciliador-v1',
  name: 'Igreja Anglicana do Reconciliador',
  shortName: 'Reconciliador',
  handle: '@anglicanadoreconciliador',
  cssClass: 'marca-reconciliador',
  assetBase: 'marcas/reconciliador/',
  allowTweaks: true,
  tweakControls: ['palette', 'accent', 'fontScale'],
  palettes: {
    pergaminho: { label: 'Pergaminho', paper: '#F7F5F1', ink: '#1F2B45' },
    areia:      { label: 'Areia',      paper: '#EFE3D2', ink: '#1F2B45' },
    navy:       { label: 'Navy',       paper: '#1F2B45', ink: '#F7F5F1' },
    vigilia:    { label: 'Vigília',    paper: '#141A28', ink: '#F7F5F1' },
  },
  accents: {
    ouro:   { label: 'Ouro',   color: '#B6956A' },
    claro:  { label: 'Claro',  color: '#D0B591' },
    bronze: { label: 'Bronze', color: '#93744E' },
    navy:   { label: 'Navy',   color: '#1F2B45' },
  },
  tweakDefaults: { palette: 'pergaminho', accent: 'ouro', fontScale: 1 },
  previewShell: 'post',
  hasCanvas: false,
  exportPixelRatio: 1,
  exportFilePrefix: 'reconciliador',
  exportBg: '#F7F5F1',
  barTheme: 'reconciliador',
  get logoIcon() { return window.ReconciliadorIcons?.IconSelo; },
  get templates() { return window.RECONCILIADOR_TEMPLATES || []; },
  get galleries() { return window.RECONCILIADOR_GALLERIES || { photos: [], icons: [] }; },
};
